name: build

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew build
