name: build and publish

on:
  push:
    branches:
      - trunk
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: |
            jakewharton/posterbox
            ghcr.io/jakewharton/posterbox
          tag-semver: |
            {{version}}
            {{major}}
            {{major}}.{{minor}}

      - uses: docker/login-action@v1
        with:
          username: jakewharton
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - run: ./gradlew build

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v1

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/dist/posterbox.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
