name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'
    tags-ignore:
      - '**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: docker build -t posterbox .

      - name: Test Docker container
        run: |
          mkdir temp
          # TODO change to just touch when https://github.com/JakeWharton/PosterBox/pull/13 lands.
          echo "itemDisplayDuration = \"PT10S\"" > temp/config.toml
          docker run -d -v `pwd`/temp:/config -p 9931:9931 --name posterbox posterbox
          # Wait for container to start up and be healthy.
          timeout 30 sh -c 'until [ "`docker inspect -f {{.State.Health.Status}} posterbox`"=="healthy" ]; do sleep 1; done;'
          curl -q localhost:9931
