name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'
    tags-ignore:
      - '**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.1.0
        with:
          distribution: 'zulu'
          java-version: 17
      - run: ./gradlew build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: docker build -t posterbox .

      - name: Test Docker container
        run: |
          mkdir temp
          touch temp/config.toml
          docker run -d -v `pwd`/temp:/config -p 9931:9931 posterbox
          # Wait for container to start up and bind to port.
          timeout 10 sh -c 'until nc -z localhost 9931; do sleep 1; done;'
          sleep 1
          curl -q localhost:9931
